In [1]:
import torch

In [2]:
scalar = torch.tensor(3.14159)
vector = torch.tensor([1,2,3])
matrix = torch.ones((2,3),dtype=torch.float)
tensor = torch.rand((2,3,4), dtype=torch.float)

print(scalar)
print(vector)
print(matrix)
print(tensor)

tensor(3.1416)
tensor([1, 2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[0.2305, 0.1352, 0.2037, 0.4160],
         [0.3664, 0.1927, 0.6727, 0.4123],
         [0.7509, 0.3321, 0.1090, 0.4798]],

        [[0.7319, 0.5573, 0.1054, 0.4624],
         [0.4167, 0.7697, 0.3491, 0.9965],
         [0.2131, 0.2159, 0.3209, 0.5304]]])


In [3]:
print(tensor.size(), tensor.shape)

torch.Size([2, 3, 4]) torch.Size([2, 3, 4])


In [4]:
print(scalar.size(), scalar.shape)

torch.Size([]) torch.Size([])


View method returns tensor with desired shape, it does not create new tensor, but shares underlying data with original tensor.

In [7]:
# reshape tensor
same_matrix = matrix.view(1,6)
# change one element of the new tensor reshaped
same_matrix[0,1] = 2

print(same_matrix)
print(matrix)

tensor([[1., 2., 1., 1., 1., 1.]])
tensor([[1., 2., 1.],
        [1., 1., 1.]])


As observed the original tensor and new reshaped tensor have changed after the update.

In [8]:
print(scalar.size(), scalar.shape)

torch.Size([]) torch.Size([])


All tensors have shapes but scalars have "empty" shapes since they are dimesionless

### Copy Tensors
To copy all data from one tensor, you can use `new_tensor()` or `clone()` methods. `new_tensor` does not change the elements of the original tensor. However pytorch recommends using `clone` instead. Running the following code will give warning to use `clone` instead.

In [9]:
new_matrix = matrix.new_tensor(matrix.view(1,6))
# change element of the new tensor
new_matrix[0,1] = 4
# original tensor is left unchanged
print(matrix)
print(new_matrix)

tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 4., 1., 1., 1., 1.]])


C:\Users\robot\AppData\Local\Temp\ipykernel_28688\2988553524.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  new_matrix = matrix.new_tensor(matrix.view(1,6))


#### Using `clone.detach` to copy tensors

In [10]:
matrix_copy = matrix.view(1,6).clone().detach()
# change one element
matrix_copy[0,1] = 5
# matrix is left unchanged (original)
print(matrix)
print(matrix_copy)


tensor([[1., 2., 1.],
        [1., 1., 1.]])
tensor([[1., 5., 1., 1., 1., 1.]])
